/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Users;

import Config.Session;
import Config.config;
import Config.passwordHasher;
import LoginPage.Login;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Raven
 */
public class changePass extends javax.swing.JFrame {

    /** Creates new form User */
    public changePass() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        idDisplay = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        header14 = new javax.swing.JPanel();
        Acc_lname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Acc_fname = new javax.swing.JLabel();
        Acc_id = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        save1 = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        oldpass = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel9.setBackground(new java.awt.Color(255, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idDisplay.setText("ID:");
        jPanel9.add(idDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 80, 30));

        jPanel10.setBackground(new java.awt.Color(51, 255, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 102)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ACCOUNT INFORMATION");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 610, 40));

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("X");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 40, 40));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        jPanel11.setBackground(new java.awt.Color(255, 255, 102));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header14.setBackground(new java.awt.Color(0,0,0,60));
        header14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Acc_lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Acc_lname.setForeground(new java.awt.Color(255, 255, 255));
        Acc_lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Acc_lname.setText("FirstName");
        Acc_lname.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header14.add(Acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gwwapo-removebg-preview.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 80));

        Acc_fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Acc_fname.setForeground(new java.awt.Color(255, 255, 255));
        Acc_fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Acc_fname.setText("Lname");
        Acc_fname.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header14.add(Acc_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        jPanel11.add(header14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 130));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 330));

        Acc_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Acc_id.setForeground(new java.awt.Color(255, 255, 255));
        Acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Acc_id.setText("ID:");
        Acc_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(Acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 30));

        save.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        save.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        save.setText("BACK");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jPanel9.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 50, 30));

        save1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        save1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save1.setText("SAVE");
        save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save1MouseClicked(evt);
            }
        });
        jPanel9.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 70, 30));

        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        jPanel9.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 150, -1));

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Confirm Pass:");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 100, -1));

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Enter New Pass");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 130, -1));
        jPanel9.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 150, -1));
        jPanel9.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 150, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("type Old Pass");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, -1));

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 670, 390);

        setSize(new java.awt.Dimension(690, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        Session ses = Session.getInstance();
         idDisplay.setText(""+ses.getId());
          

    }//GEN-LAST:event_formWindowActivated

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked

        accountDetails cp = new accountDetails();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveMouseClicked

    private void save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseClicked
         
          try{
          config conf = new config();
           Session ses = Session.getInstance();
         
          String query = "SELECT * from users WHERE id = '"+ses.getId()+"'";
            ResultSet rs = conf.getData(query);
            
           
            if(rs.next()){
                
             String  olddbpass=rs.getString("pname");
               String oldhash = passwordHasher.hashPassword(oldpass.getText());
               if(olddbpass.equals(oldhash)){
                   String npass=passwordHasher.hashPassword(newpass.getText());
                   conf.updateData("UPDATE users SET pname ='"+npass+"' ");
                    JOptionPane.showMessageDialog(null,"wohoah Updates Succesfully!");
                        Login lg = new Login();
                        lg.setVisible(true);
                        this.dispose();
               }else{
                   JOptionPane.showMessageDialog(null,"Old password is incorrect!");
               }
                
            }
       }catch(SQLException | NoSuchAlgorithmException ex){
           System.out.println(""+ ex);
       }
        

    }//GEN-LAST:event_save1MouseClicked

    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acc_fname;
    private javax.swing.JLabel Acc_id;
    private javax.swing.JLabel Acc_lname;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JPanel header14;
    private javax.swing.JLabel idDisplay;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JTextField oldpass;
    private javax.swing.JLabel save;
    private javax.swing.JLabel save1;
    // End of variables declaration//GEN-END:variables

}
